### ISSUE TITLE
CAN WORKAROUND_MDR32F9QX_ERROR_0002 - IRQ enable loose

### ISSUE THREAD

**Issue by alexrayne** [in4lio/mdr1986x-pack-repo#2]
MDR32F9Qx_can have code for WORKAROUND_MDR32F9QX_ERROR_0002: CAN_ReadBufferSFR
this routime disables interupts, and enables it without mention of enable state before call.
therefore, if GIE was disabled before CAN_xxxx routine call, it will be enabled after surprisingly

**Comment by in4lio** [comment]
Hi @alexrayne -- please, report this issue in the library repo: https://github.com/eldarkg/emdr1986x-std-per-lib/issues
